### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by JohnSasser** [PlatinumJdog/Learns#2]
Looks pretty damn good!  
Try this update and we will review later. Nested looping is a complex and nuanced thing, so don’t fixate on understanding before we go over it and you have written more code. 
Awesome job. 

`//Guess from Player
            var guess = prompt("Guess a letter, or click Cancel to stop playing");
            if (guess === null) {
//Exit the game loop
                break;
            } else if (guess.length !== 1) {
                alert("Please enter a single letter.");
            } 
//Update state of game based on Player's guess
            else {
                for (var i = 0; i < word.length; i++) {
                    if (word[i] === guess) {
                        answerArray[i] = guess;
                        remainingLetters--;
                    }
                }
            }
 `

**Comment by PlatinumJdog** [comment]
Changed the J to I and moved the comment above to else. I realize that the comment being below the Else and above the IF
slightly confuses me when I look back at it. Will read further into the Nesting.
